# serverless.yml

service: sls-import-functions

plugins:
 - serverless-external-s3-event

provider:
  name: aws
  stage: dev
  region: us-east-1
  role: arn:aws:iam::326806802576:role/serverlessadmin
  runtime: nodejs6.10
  timeout: 300
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-deploy
  environment:
    AWS_BUCKET: xxxHEREBUCKETNAMExxx
    AWS_QUEUE_URL: xxxHERESQSURLxxx
    CUSTOMER_NAME: xxxHERECUSTOMERNAMExxx

# Functions declaration
functions:
  producerImports:
    handler: src/producer/handler.producer
    description: read imports from s3 csv file.
    environment:
      AWS_S3_BUCKET: ${self:provider.environment.AWS_BUCKET}
      AWS_QUEUE_URL: ${self:provider.environment.AWS_QUEUE_URL}
      CUSTOMER_NAME: ${self:provider.environment.CUSTOMER_NAME}
    events:
      - existingS3:
          bucket: ${self:provider.environment.AWS_BUCKET}
          events:
            - s3:ObjectCreated:*
          rules:
            #- prefix: 
            - suffix: .csv

# Events Lambda invoke permissions.
resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
          Action: lambda:InvokeFunction
          FunctionName: ${self:service}-${self:provider.stage}-producerImports
          Principal: s3.amazonaws.com
          SourceArn: arn:aws:s3:::${self:provider.environment.AWS_BUCKET}