# serverless.yml

service: lambdaimports

provider:
  name: aws
  role: arn:aws:iam::084187035577:role/serverlessadmin
  runtime: nodejs6.10
  timeout: 300

functions:
  producerImports:
    handler: src/producer/handler.producer
    description: read imports from s3 csv file.
    environment:
      AWS_S3_BUCKET: envistasecure
      AWS_QUEUE_NAME: importsqueue